name: LT-VT CI
on: [pull_request, push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm install

      - name: Set  Test ENV
        run : node set_env.js
      - name: Run Test
        run : node test.js
      - name: Update Test
        run : node update_status.js

     
