name: LT-VT CI- develop
on: 
  repository_dispatch:
    types: [build]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: Run Test
        run : node test.js
     
