name: Checkout repos
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
      - name: checkout
      - uses: actions/checkout@master      
      - name: npm dependencies
        run: npm install     
      - name: Nodejs
        run: node test.js  
