name: LT-VT CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: LT Test
        run: node test.js
      - name: LT-V
        uses: Shivanshu-lambdatest/Github-VT-Plugin@Review-Check-v1
        env: GITHUB_TOKEN:${{ secrets.GITHUB_TOKEN }}

     
