name: LT-VT CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: LT Test
        uses: percy/exec-action@master
        with:
          command: "node test.js"
     
