name: LT-VT CI
on: [repository_dispatch]
 #types: [on-demand-test]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: LT Test
        run: node test.js
